config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[create]
  end

  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[create]

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render '/lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render "shared/banner", name: "Organize your movies", image: "banner.jpg" %>

<div class="container">
  <div class="cards my-3">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
        <%= render "shared/card_category", name: list.name, image_url: list.image_url %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div data-controller="update-banner">
  <%= render "shared/banner", name: "Create a new list", image: "banner.jpg" %>

  <div class="container my-5">
    <div class="row justify-content-md-center mt-5">
      <div class="col col-sm-6 bg-white py-3">
        <%= simple_form_for(@list, data: { action: "input->update-banner#update", update_banner_target: "form" }) do |f| %>
          <%= f.input :name %>
          <%= f.input :image_url %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%= render "/shared/banner", name: @list.name, image: @list.image_url, movie_count: @list.bookmarks.count %>

<div class="container">
  <div class="cards my-3">
    <% @list.bookmarks.each do |bookmark| %>
      <%= render "shared/card_trip", bookmark: bookmark %>
    <% end %>
  </div>

  <div class="row justify-content-md-center mt-5">
    <div class="col col-sm-6 bg-white pt-3">
      <h2>Add a new movie</h2>
    </div>
  </div>
  <div class="row justify-content-md-center mb-5">
    <div class="col col-sm-6 bg-white pb-3">
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment %>
        <%= f.association :movie %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" data-update-banner-target="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path image %>);">
  <div class="container">
    <h1 class="text-center"><%= name %></h1>
  </div>
  <% if local_assigns[:movie_count] && movie_count.positive? %>
    <p id="count"><%= movie_count %> movie<% if movie_count > 1 %>s<% end %></p>
  <% end %>
</div>

app/views/shared/_card_category.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_url %>)">
  <%= name %>
</div>

app/views/shared/_card_trip.html.erb
<div class="card-trip">
  <img src=<%= bookmark.movie.poster_url %> />
  <div class="card-trip-infos">
    <div>
      <h2><%= bookmark.movie.title %> - <%= bookmark.movie.rating %> ⭐</h2>
      <p><%= bookmark.movie.overview %></p>
    </div>
    <div class="card-trip-infos-bottom">
      <strong><i class="fa-solid fa-quote-right"></i> <%= bookmark.comment %></strong>
      <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete } do %>
        <strong class="card-trip-pricing text-danger">delete</strong>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "watch-list-icon-120x120.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My lists", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New list", new_list_path, class: "nav-link" %>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>